=== java-search-engine-framework/scany-test/conf/dtd/scany-2.0.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT scany (local?, client?, server?)>

<!ELEMENT schema (#PCDATA)>
<!ELEMENT directory (#PCDATA)>
<!ELEMENT characterEncoding (#PCDATA)>

<!ELEMENT local (directory, schema, characterEncoding?, spooling?)>

<!ELEMENT spooling (directory? | ftp? | jdbc? | jndi?)>

<!ELEMENT ftp (connection, user, directory)>
<!ELEMENT user (id, password)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ATTLIST password
encryption CDATA #IMPLIED
>

<!ELEMENT jdbc (#PCDATA)>
<!ELEMENT jndi (#PCDATA)>

<!ELEMENT client (local? | remote?)>
<!ELEMENT remote (tcp? | http?)>

<!ELEMENT tcp (connection, message?)>

<!ELEMENT connection (host, timeout?)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host
port CDATA #REQUIRED
>
<!ELEMENT timeout (#PCDATA)>

<!ELEMENT message (keysign, body?)>
<!ATTLIST message
format (xml | json | binary) #IMPLIED
encoding CDATA #IMPLIED
>

<!ELEMENT keysign (#PCDATA)>
<!ATTLIST keysign
encryption (true | false) #IMPLIED
compressable (true | false) #IMPLIED
>

<!ELEMENT body EMPTY>
<!ATTLIST body
encryption (true | false) #IMPLIED
compressable (true | false) #IMPLIED
>

<!ELEMENT http (url, timeout?, message)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT server (remote, optimizing?)>
<!ELEMENT optimizing (#PCDATA)>

=== java-search-engine-framework/scany-test/conf/backup/scany-20111122.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE scany PUBLIC "-//JHLabs.org//DTD scany 2.0//EN"
                           "./dtd/scany-2.0.dtd">

<scany>

	<local>
		<schema></schema>
		<directory></directory>
		<characterEncoding>utf-8</characterEncoding>
		<spooling>
			<directory></directory>
		</spooling>
	</local>

	<client>
		<remote>
			<http>
				<url>http://</url>
				<message format="json" encoding="utf-8">
					<keysign encryption="none">1234</keysign>
					<body compressable="true"/>
				</message>
			</http>
		</remote>
	</client>

	<server>
		<remote>
			<tcp>
				<connection>
					<host port=""/>
					<timeout>2000</timeout>
				</connection>
				<message format="xml" encoding="utf-8">
					<keysign encryption="none">1234</keysign>
					<body compressable="true"/>
				</message>
			</tcp>
		</remote>
		<optimizing>
			
		</optimizing>
	</server>

</scany>
