=== java-search-engine-framework/scany-test/conf/dtd/schema-2.0.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT schema (analyzers?, summarizers?, queryTextParsers?, relation*)>

<!ELEMENT analyzers (analyzer*)>
<!ELEMENT analyzer (properties?)>
<!ATTLIST analyzer
id CDATA #REQUIRED
class CDATA #REQUIRED
>

<!ELEMENT properties (property*)>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property
name CDATA #REQUIRED
>

<!ELEMENT summarizers (summarizer*)>
<!ELEMENT summarizer (properties?)>
<!ATTLIST summarizer
id CDATA #REQUIRED
class CDATA #REQUIRED
>

<!ELEMENT queryTextParsers (queryTextParser*)>
<!ELEMENT queryTextParser (properties?)>
<!ATTLIST queryTextParser
id CDATA #REQUIRED
class CDATA #REQUIRED
>

<!ELEMENT relation (description, directory, recordKey, attributes)>
<!ATTLIST relation
id CDATA #REQUIRED
analyzer CDATA #REQUIRED
queryTextParser CDATA #IMPLIED
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT directory (#PCDATA)>
<!ATTLIST directory
relative (true | false) #IMPLIED
>

<!ELEMENT recordKey (#PCDATA)>
<!ATTLIST recordKey
join CDATA #IMPLIED
>

<!ELEMENT attributes (attribute*)>

<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
name CDATA #REQUIRED
nullable (true | false) #IMPLIED
storable (true | false) #IMPLIED
indexable (true | false) #IMPLIED
analyzable (true | false) #IMPLIED
queryable (true | false) #IMPLIED
termVector (no | yes | withPositions | withOffsets | withPositionsOffsets | all) #IMPLIED
boost CDATA #IMPLIED
analyzer CDATA #IMPLIED
summarizer CDATA #IMPLIED
>

=== java-search-engine-framework/scany-test/conf/schema.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE schema PUBLIC "-//JHLabs.org//DTD Schema 2.0//EN"
                        "./dtd/schema-2.0.dtd">
                           
<schema>

	<analyzers>
		<analyzer id="bigram" class="org.jhlabs.scany.engine.analysis.bigram.BigramAnalyzer"/>
		<analyzer id="csv" class="org.jhlabs.scany.engine.analysis.csv.CSVAnalyzer"/>
		<analyzer id="syllabic" class="org.jhlabs.scany.engine.analysis.syllabic.SyllabicAnalyzer"/>
		<analyzer id="kr" class="org.jhlabs.scany.engine.analysis.kr.KoreanAnalyzer">
			<properties>
				<property name="characterEncoding">UTF-8</property>
				<property name="dictionaryLocation">/c:/ADE_JHLabs/workspace/scany-test/dic</property>
				<property name="bigrammable">true</property>
			</properties>
		</analyzer>
	</analyzers>
	
	<summarizers>
		<summarizer id="summarizer" class="org.jhlabs.scany.engine.search.summarize.SimpleFragmentSummarizer">
			<properties>
				<property name="highlightOpenTag">&lt;strong style='color:red'&gt;</property>
				<property name="highlightCloseTag">&lt;/strong&gt;</property>
			</properties>
		</summarizer>
	</summarizers>
	
	<queryTextParsers>
		<queryTextParser id="queryTextParser" class="org.jhlabs.scany.engine.search.query.SimpleQueryTextParser"/>
	</queryTextParsers>
	
	<relation id="relation01" analyzer="kr" queryTextParser="queryTextParser">
		<description>공지사항</description>
		<directory relative="true"/>
		<recordKey join="$">boardId$articleId</recordKey>
		<attributes>
			<attribute name="boardId"
				nullable="false" storable="true" indexable="true" analyzable="false"
				>게시판ID</attribute>
			<attribute name="articleId"
				nullable="false" storable="true" indexable="true" analyzable="false"
				>글ID</attribute>
			<attribute name="group"
				nullable="false" storable="true" indexable="true" analyzable="false"
				>게시판그룹</attribute>
			<attribute name="category"
				nullable="false" storable="true" indexable="true" analyzable="false"
				>분류</attribute>
			<attribute name="title"
				nullable="false" storable="true" indexable="true" analyzable="true" queryable="true" termVector="all"
				boost="1.1"
				analyzer="syllabic"
				>제목</attribute>
			<attribute name="content"
				nullable="true" storable="true" indexable="true" analyzable="true" queryable="true" termVector="all"
				summarizer="summarizer"
				boost="1.0"
				analyzer="kr"
				>내용</attribute>
			<attribute name="tag"
				nullable="false" storable="true" indexable="true" analyzable="true" queryable="true" termVector="all"
				boost="1.2"
				analyzer="csv"
				>태그</attribute>
			<attribute name="writer"
				nullable="false" storable="true" indexable="true" analyzable="false"
				>작성자</attribute>
			<attribute name="date"
				nullable="false" storable="true" indexable="true" analyzable="false"
				>등록일자</attribute>
			<attribute name="url"
				nullable="true" storable="true" indexable="false" analyzable="false"
				>URL</attribute>
		</attributes>
	</relation>

</schema>
